//手搓i18n
var cur_num;
var quicknote = 0; //闪念模式
var stick = 0; //固定顶栏
var about = 0; //“关于”栏
var settings = 0; //设置栏
var DARK,
  LIGHT,
  ON,
  OFF,
  SAVED_AT,
  AUTO_SAVED_AT,
  CHOOSE_FILE,
  NEW,
  ENSURE_DEL,
  YES,
  OK,
  FNAME,
  FBLINK = "https://support.qq.com/products/174144",
  SEARCH,
  REPLACE,
  SEARCHTIP,
  RWITH,
  CREATE_FROM_FILE,
  RELSE_MOUSE,
  DRAG_HERE,
  SUCCEED,
  ALL,
  CANCEL,
  SKIP,
  PREVIEW,
  OR,
  CLICK_TO_UPLOAD,
  COUNT,
  WORD,
  CHAR,
  TIME,
  WITH_SPACE,
  SAVE_AS,
  CHOOSE_MAIN_COLOR,
  DIY_COLOR,
  SET_TO_DEFALT,
  AUTO,
  WITH_STYLE,
  QUICK_NOTE,
  TERM,
  DEFALT,
  THIS_IS_A_BACKUP,
  FILE_LIST_TITLE,
  NOTHING_TO_COUNT,
  MAXMIZE,
  RESTORE,
  NEW_VER,
  UPDATE_NOW,
  SHOW_NEXT_TIME,
  DONT_SHOW_AGAIN,
  REPLACE_CURR_DATA,
  IMPORT_CANCELED,
  COLLECTING_DATA,
  SENDING_DATA,
  SEND_SUCCEEDED,
  NET_ERR,
  PULLING_LIST,
  CHOOSE_BACKUP,
  DOWNLOADING_DATA,
  PARSING_DATA,
  NEWEST,
  FILE_BROKEN,
  GENERATE,
  SYNC_FAILED,
  SYNC_FAILED_REASON;

function set_lang_to(lang) {
  //用于初始化语言的函数
  switch (lang) {
    case "en":
      DARK = "Dark";
      LIGHT = "Light";
      ON = "On";
      OFF = "Off";
      SAVED_AT = "Saved at ";
      AUTO_SAVED_AT = "Automatically saved at ";
      CHOOSE_FILE = "Choose an essay";
      NEW = "New";
      ENSURE_DEL = "Are you sure? It is IRREVERSIBLE.";
      YES = "Yes";
      OK = "OK";
      FNAME = "Rename";
      SEARCH = "Search";
      REPLACE = "Replace";
      SEARCHTIP = "Use /re/ syntax for regex search. <br />Press Esc to Exit.";
      RWITH = "With";
      RELSE_MOUSE = "release the mouse button";
      DRAG_HERE = "Drag your file here";
      CREATE_FROM_FILE = "Create an essay from a local file...";
      SUCCEED = "Your file has uploaded successfully";
      ALL = "All";
      CANCEL = "Cancel";
      SKIP = "Skip";
      PREVIEW = "Preview";
      OR = "or";
      CLICK_TO_UPLOAD = "Click to choose a file";
      COUNT = "Count";
      WORD = "Words";
      CHAR = "Chars";
      TIME = "Expected reading time";
      WITH_SPACE = " (with spaces)";
      NO_WHEN_MSGBOX = "Commands can not be executed when a dialog is open";
      SAVE_AS = "Save as...";
      CHOOSE_MAIN_COLOR = "Choose your main color";
      DIY_COLOR = "Pick a color...";
      SET_TO_DEFALT = "Set to defalt";
      AUTO = "Follow the OS";
      WITH_STYLE = " (with styles)";
      QUICK_NOTE = "Quick note";
      TERM = "Monospaced font";
      DEFALT = "Normal font";
      THIS_IS_A_BACKUP =
        "This is a backup file of Clear Writer, including all the user's all passages and settings except the user's account data. You can learn more about it on [the website of Clear Writer](https://henrylin666.gitee.io/clearwriter/). This backup file was created by Clear Writer version ${VERSION} on ${date}.";
      FILE_LIST_TITLE = "Essay List";
      NOTHING_TO_COUNT = "There is nothing to count";
      MAXMIZE = "Maxmize";
      RESTORE = "Restore";
      NEW_VER = "A New Version Detected - ";
      UPDATE_NOW = "Update now";
      SHOW_NEXT_TIME = "Show me next time";
      DONT_SHOW_AGAIN = "Do not prompt this version again";
      REPLACE_CURR_DATA =
        "Would you like to replace all current data with this backup?";
      IMPORT_CANCELED = "Import canceled";
      COLLECTING_DATA = "Collecting data";
      SENDING_DATA = "Sending data";
      SEND_SUCCEEDED = "Data sending succeeded";
      NET_ERR = "Network exception, please try again";
      PULLING_LIST = "Pulling backup list";
      CHOOSE_BACKUP = "Choose a backup";
      DOWNLOADING_DATA = "Downloading data";
      PARSING_DATA = "Parsing data";
      NEWEST = "The current version is the latest version";
      FILE_BROKEN = "The file was broken";
      GENERATE =
        "Generated by <a href='https://clearwriter.gitee.io/'>Clear Writer</a>";
      SYNC_FAILED = "Sync Failed";
      SYNC_FAILED_REASON =
        "This is not a problem with Clear Writer. the Gitee server is returning 500 errors, which indicates that the server is unable to process your essays. <br/>Gitee's sync service does not support emoji and some special characters, but Gitee doesn't specify which characters may cause these problems. So you may need to look for the characters in your essays yourself that may cause errors. You might also consider using the Github Gist service.";

      $("#title_of_theme").html("Theme");
      $("#title_of_num").html("Line numbers");
      $("#title_of_lang").html("Language");
      $("#lang").html("English (US)");
      $("#save_btn").html("Save as...");
      $("#about").html(
        '<h1 id="h1-welcome-to-clear-writer-an-immersive-markdown-writing-software-"><a name="Welcome to Clear Writer, an immersive Markdown writing software." class="reference-link"></a><span class="header-link octicon octicon-link"></span>Welcome to Clear Writer, an immersive Markdown writing software.</h1><h2 id="h2-why-to-write-clear-writer"><a name="Why to write Clear Writer" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Why to write Clear Writer</h2><p>After starting my own blog, I’ve been struggling with the lack of a Markdown editor on the Windows that I like.</p><blockquote><p>Actually, we don’t need a very powerful tool for writing. All we need is an environment that can make us not easily distracted.</p></blockquote><p>iA Writer certainly does this well, but as a student, I really didn’t have the means to buy the software. And I don’t plan to use piracy either. I found a silimar software called <a href="http://write4Me.sinaapp.com/">4Me Writer</a>. It is based on CodeMirror, but the difference between it and iA Writer is a bit large….</p><p>But it did inspire me: why not try making a Markdown editor with CodeMirror myself?</p><p>So after asking the original author’s permission, I took the time to try to make my own writing tool using the 4Me writing board as a model. So I made this Markdown editor — Clear Writer — meaning that I wanted people to use it so that they could clear their minds.</p><p>Also, a very important thing about Clear Writer is that it supports real-time Markdown preview. A lot of the so-called real-time Markdowns, I’m not a big fan of - because they hide the Markdown format markup. I don’t like that, I like to keep the format firmly in the hands of the user.</p><h2 id="h2-features-of-clear-writer"><a name="Features of Clear Writer" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Features of Clear Writer</h2><ul><li>Fully automated preservation.</li><li>Real-time MarkDown for WYSIWYG, and title hanging.</li><li>Support bright/dark mode.</li><li>Nice scroll bar.</li><li>Support Simplified Chinese / Traditional Chinese / English.</li><li>Support for turning line numbers on/off.</li><li>Highlight the current paragraph.</li><li>Beautiful cursor flickering and jumping effects.</li><li>Interface adaptation.</li><li>All content is cached locally, with full privacy protection.</li><li>Support for exporting <code>.txt</code>, <code>.md</code>, <code>.doc</code>, <code>.html</code>, <code>html (with CSS)</code> in 5 formats.</li><li>Smooth rolling.</li><li>Quick note (v1.7+) that puts you in a writing state immediately.</li></ul><h2 id="h2-tips-for-using"><a name="Tips for using" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Tips for using</h2><ul><li>Writing with peace of mind by clicking the full screen button on the title bar or by pressing <code>F11</code> (or <code>Fn + F11</code>) to go full screen.</li><li>The top bar is displayed when the mouse is moved to the top, where it is possible to switch between light/dark modes, line numbers, language, etc.</li><li>The top bar can be fixed so that it is not automatically hidden by clicking the <code>📌</code> button on the top bar.</li><li>The upper right corner has the <code>Save as...</code> button, which allows the text to be exported to other text formats.</li><li>Clicking on <code>Clear Writer</code> in the upper left corner will display the text you are reading right now — this article — in the sidebar, and clicking on <code>Clear Writer</code> again will hide the sidebar.</li><li>The last 2000 operations can be revoked without fear of modification.</li><li>Clear Writer saves automatically, normally every 3 minutes, and again when it is closed. If you are not sure, you can also save it manually by <code>Ctrl + S</code>.</li><li>Search: <code>Ctrl + F</code>.</li><li>Find the next one: <code>Ctrl + G</code>.</li><li>Find previous: <code>Shift + Ctrl + G</code>.</li><li>Replace: <code>Shift + Ctrl + F</code>.</li><li>Replace all: <code>Shift + Ctrl + R</code>.</li></ul><h2 id="h2-compatibility"><a name="Compatibility" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Compatibility</h2><p>Windows 7+.</p><h2 id="h2-about-"><a name="About." class="reference-link"></a><span class="header-link octicon octicon-link"></span>About.</h2><p>Clear Writer is licensed under the GNU General Public License 3.0.</p><p>Coding tool: Visual Studio & Visual Studio Code<br>Installer creation tool: NSIS</p><h3 id="h3-clear-writer-was-born-from-"><a name="Clear Writer was born from." class="reference-link"></a><span class="header-link octicon octicon-link"></span>Clear Writer was born from:</h3><ul><li>Font: NeverMind (SIL Open Font License 1.1), Sarasa Gothic (SIL Open Font License 1.1).</li><li>Editor base: CodeMirror (MIT License).</li><li>Markdown rendering: editor.md (MIT License).</li><li>Building blocks: Electron (MIT License).</li><li>Icons: Font Awsome (Font Awesome Free License).</li><li>Blueprint: 4Me Writer, no agreement status, but has been orally licensed by the developer.</li></ul><p>Thanks to all those who have supported and helped with this project.</p>'
      );
      $("#copy").html("Copy");
      $("#paste").html("Paste");
      $("#cut").html("Cut");
      $("#selectall").html("Select all");
      $("#bold").html("Bold");
      $("#italic").html("Italic");
      $("#linethrough").html("Strike through");
      $("#hyperlink").html("Hyper link");
      $("#undo").html("Undo");
      $("#redo").html("Redo");
      $("#title_of_main_color").html("Main color");
      $("#fold").html("Fold");
      $("#advance").html("Advanced");
      $("#title_of_disable_animation").html("Disable animations");
      $("#title_of_settings").html("Settings");
      $("#title_of_look").html("Appearance");
      $("#set_main_color").html("Set...");
      $("#title_of_font").html("Font");
      $("#experiment").html("Experiments");
      $("#experiment-warning").html(
        "WARNING: EXPERIMENTAL FEATURES AHEAD! By enabling these features, Clear Writer may be instable."
      );
      $("#title_of_acrylic").html("Enable arylic (Win10 1803+)");
      $("#title_of_opacity").html("Background opacity");
      $("#title_of_dev").html("Dev tools");
      $("#dev_tools").html("Open");
      $("#backup_and_sync").html("Backup & Sync");
      $("#import_from_file").html("Import data");
      $("#export_to_file").html("Export data");
      $("#sync_start_btn").html("Sign in with a Github account");
      $("#sync_upload").html("Upload data");
      $("#sync_download").html("Download data");
      $("#gitee_sync_start_btn").html("Sign in with a Gitee account");
      $("#gitee_sync_upload").html("Upload data");
      $("#gitee_sync_download").html("Download data");
      $("#title_of_css").html("Custom CSS");
      $("#css_btn").html("Edit...");
      $("#title_of_update").html("Updates");
      $("#update").html("Check for updates");
      $("#current_vertion").html(`Current Version: ${VERSION}`);
      $("#open").attr("title", "Open the essay list【Ctrl + O】");
      $("#feedback").attr("title", "Give feedback");
      $("#open_settings").attr("title", "Open settings");
      $("#topbar_undo").attr("title", "Undo【Ctrl + Z】");
      $("#topbar_redo").attr("title", "Redo【Ctrl + Y or Ctrl + Shift + Z】");
      $("#topbar_bold").attr(
        "title",
        '#Bold#Use a pair of "**" or a pair of "__" to wrap the bold text【Ctrl + B】'
      );
      $("#topbar_italic").attr(
        "title",
        '#Italic#Use a pair of "*" or a pair of "_" to wrap the italic text【Ctrl + I】'
      );
      $("#topbar_strikethrough").attr(
        "title",
        '#Strike through#Use a pair of "~~" to wrap the text you want to strike through【Ctrl + I】'
      );
      $("#topbar_link").attr(
        "title",
        'Hyper link#Use a pair of "[" and "]" to wrap the text, following by a URL wrapped with "(" and ")"【Ctrl + I】'
      );
      $("#find").attr("title", "Search【Ctrl + F】");
      $("#replace").attr("title", "Replace【Ctrl + H or Ctrl + Shift + F】");
      $("#preview").attr("title", "Preview");
      $("#counter").attr("title", "Counter");
      $("#title").attr("title", "About");
      $("#save_btn").attr("title", "#Save as#Save the essay as a file.");
      $("#minimize").attr("title", "Minimize");
      $("#maxmize").attr("title", "Maximize");
      $("#fullscreen").attr("title", "Fullscreen");
      $("#close").attr("title", "Close");
      $("#gitee_sign_out_btn").attr("title", "Sign out");
      $("#sign_out_btn").attr("title", "Sign out");
      break;
    case "en_uk":
      set_lang_to("en");
      CHOOSE_MAIN_COLOR = "Choose your main colour";
      DIY_COLOR = "Pick a colour...";
      IMPORT_CANCELED = "Import cancelled";
      $("#title_of_main_color").html("Main colour");
      $("#lang").html("English (UK)");
      $("#about").html(
        '<h1 id="h1-welcome-to-clear-writer-an-immersive-markdown-writing-software-"><a name="Welcome to Clear Writer, an immersive Markdown writing software." class="reference-link"></a><span class="header-link octicon octicon-link"></span>Welcome to Clear Writer, an immersive Markdown writing software.</h1><h2 id="h2-why-to-write-clear-writer"><a name="Why to write Clear Writer" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Why to write Clear Writer</h2><p>After starting my own blog, I’voe been struggling with the lack of a Markdown editor on the Windows that I like.</p><blockquote><p>Actually, we don’t need a very powerful tool for writing. All we need is an environment that can make us not easily distracted.</p></blockquote><p>iA Writer certainly does this well, but as a student, I really didn’t have the means to buy the software. And I don’t plan to use piracy either. I found a silimar software called <a href="http://write4Me.sinaapp.com/">4Me Writer</a>. It is based on CodeMirror, but the difference between it and iA Writer is a bit large….</p><p>But it did inspire me: why not try making a Markdown editor with CodeMirror myself?</p><p>So after asking the original author’s permission, I took the time to try to make my own writing tool using the 4Me writing board as a model. So I made this Markdown editor — Clear Writer — meaning that I wanted people to use it so that they could clear their minds.</p><p>Also, a very important thing about Clear Writer is that it supports real-time Markdown preview. A lot of the so-called real-time Markdowns, I’m not a big fan of - because they hide the Markdown format markup. I don’t like that, I like to keep the format firmly in the hands of the user.</p><h2 id="h2-features-of-clear-writer"><a name="Features of Clear Writer" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Features of Clear Writer</h2><ul><li>Fully automated preservation.</li><li>Real-time MarkDown for WYSIWYG, and title hanging.</li><li>Support bright/dark mode.</li><li>Nice scroll bar.</li><li>Support Simplified Chinese / Traditional Chinese / English.</li><li>Support for turning line numbers on/off.</li><li>Highlight the current paragraph.</li><li>Beautiful cursor flickering and jumping effects.</li><li>Interface adaptation.</li><li>All content is cached locally, with full privacy protection.</li><li>Support for exporting <code>.txt</code>, <code>.md</code>, <code>.doc</code>, <code>.html</code>, <code>html (with CSS)</code> in 5 formats.</li><li>Smooth rolling.</li><li>Quick note (v1.7+) that puts you in a writing state immediately.</li></ul><h2 id="h2-tips-for-using"><a name="Tips for using" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Tips for using</h2><ul><li>Writing with peace of mind by clicking the full screen button on the title bar or by pressing <code>F11</code> (or <code>Fn + F11</code>) to go full screen.</li><li>The top bar is displayed when the mouse is moved to the top, where it is possible to switch between light/dark modes, line numbers, language, etc.</li><li>The top bar can be fixed so that it is not automatically hidden by clicking the <code>📌</code> button on the top bar.</li><li>The upper right corner has the <code>Save as...</code> button, which allows the text to be exported to other text formats.</li><li>Clicking on <code>Clear Writer</code> in the upper left corner will display the text you are reading right now — this article — in the sidebar, and clicking on <code>Clear Writer</code> again will hide the sidebar.</li><li>The last 2000 operations can be revoked without fear of modification.</li><li>Clear Writer saves automatically, normally every 3 minutes, and again when it is closed. If you are not sure, you can also save it manually by <code>Ctrl + S</code>.</li><li>Search: <code>Ctrl + F</code>.</li><li>Find the next one: <code>Ctrl + G</code>.</li><li>Find previous: <code>Shift + Ctrl + G</code>.</li><li>Replace: <code>Shift + Ctrl + F</code>.</li><li>Replace all: <code>Shift + Ctrl + R</code>.</li></ul><h2 id="h2-compatibility"><a name="Compatibility" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Compatibility</h2><p>Windows 7+.</p><h2 id="h2-about-"><a name="About." class="reference-link"></a><span class="header-link octicon octicon-link"></span>About.</h2><p>Clear Writer is licenced under the GNU General Public Licence 3.0.</p><p>Coding tool: Visual Studio & Visual Studio Code<br>Installer creation tool: NSIS</p><h3 id="h3-clear-writer-was-born-from-"><a name="Clear Writer was born from." class="reference-link"></a><span class="header-link octicon octicon-link"></span>Clear Writer was born from:</h3><ul><li>Font: NeverMind (SIL Open Font Licence 1.1), Sarasa Gothic (SIL Open Font Licence 1.1).</li><li>Editor base: CodeMirror (MIT Licence).</li><li>Markdown rendering: editor.md (MIT Licence).</li><li>Building blocks: Electron (MIT Licence).</li><li>Icons: Font Awsome (Font Awesome Free Licence).</li><li>Blueprint: 4Me Writer, no agreement status, but has been orally licenced by the developer.</li></ul><p>Thanks to all those who have supported and helped with this project.</p>'
      );
      break;
    case "zh-hk":
      ON = "開";
      OFF = "關";
      SAVED_AT = "已存儲於 ";
      AUTO_SAVED_AT = "已自動存儲於 ";
      CHOOSE_FILE = "選擇隨筆";
      NEW = "新建";
      ENSURE_DEL = "確定永久删除？此操作不可撤銷。";
      OK = YES = "確定";
      SEARCH = "蒐索";
      REPLACE = "替換";
      SEARCHTIP = "使用 /re/ 語法以使用規則運算式蒐索，<br />按下 Esc 以退出";
      RWITH = "替換為";
      CREATE_FROM_FILE = "從檔案新建...";
      RELSE_MOUSE = "放開滑鼠";
      DRAG_HERE = "將檔案拖到此處";
      SUCCEED = "讀取成功";
      SKIP = "跳過";
      PREVIEW = "預覽";
      DARK = "暗";
      LIGHT = "亮";
      FNAME = "重命名";
      ALL = "全部";
      CANCEL = "取消";
      OR = "或";
      CLICK_TO_UPLOAD = "點此打開隨筆";
      COUNT = "統計";
      WORD = "字詞數";
      CHAR = "字元數";
      TIME = "預期閱讀時間";
      WITH_SPACE = " (包含空格)";
      NO_WHEN_MSGBOX = "對話方塊打開時無法執行命令";
      SAVE_AS = "另存為...";
      CHOOSE_MAIN_COLOR = "選擇主題色";
      DIY_COLOR = "選擇顏色...";
      SET_TO_DEFALT = "設為預設值";
      AUTO = "跟隨系統";
      WITH_STYLE = "（帶有樣式）";
      QUICK_NOTE = "速記";
      TERM = "等寬字體";
      DEFALT = "預設字體";
      THIS_IS_A_BACKUP =
        "這是 Clear Writer 編輯器的資料備份檔案，其中包含了用戶除登入資訊外的所有文章和用戶設置。你可以在 [Clear Writer 的官方網站](https://henrylin666.gitee.io/clearwriter/)瞭解到更多資訊。此備份由 Clear Writer 版本 ${VERSION} 創建於 ${date}。";
      FILE_LIST_TITLE = "隨筆清單";
      NOTHING_TO_COUNT = "沒有可供統計的文字";
      MAXMIZE = "最大化";
      RESTORE = "還原";
      NEW_VER = "檢測到新版本 - ";
      UPDATE_NOW = "立即更新";
      SHOW_NEXT_TIME = "下次一定";
      DONT_SHOW_AGAIN = "此版本不再提示";
      REPLACE_CURR_DATA = "確定覆蓋當前數據？";
      IMPORT_CANCELED = "導入已取消";
      COLLECTING_DATA = "正在準備數據";
      SENDING_DATA = "正在發送數據";
      SEND_SUCCEEDED = "已成功備份至雲端";
      NET_ERR = "網絡异常，請重試";
      PULLING_LIST = "正在拉取備份清單";
      CHOOSE_BACKUP = "選擇一個備份";
      DOWNLOADING_DATA = "正在下載數據";
      PARSING_DATA = "正在解析數據";
      NEWEST = "當前已是最新版本";
      FILE_BROKEN = "檔案已損壞";
      GENERATE =
        "使用 <a href='https://clearwriter.gitee.io/'>Clear Writer</a> 生成";
      $("#title_of_theme").html("主題");
      $("#title_of_num").html("行號");
      $("#title_of_lang").html("語言");
      $("#lang").html("繁體中文");
      $("#save_btn").html("另存為...");
      $("#about").html(
        '<h1 id="h1-welcome-to-clear-writer-markdown-"><a name="Welcome to Clear Writer，這是一個沉浸式 Markdown 寫作軟件。" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Welcome to Clear Writer，這是一個沉浸式 Markdown 寫作軟件。</h1><h2 id="h2--clear-writer"><a name="為什麼編寫 Clear Writer" class="reference-link"></a><span class="header-link octicon octicon-link"></span>為什麼編寫 Clear Writer</h2><p>我開了我自己的部落格之後，一直苦於Windows端沒有我喜歡的Markdown編輯器。</p><blockquote><p>其實寫作，最需要的並不是很好很强大的工具，而是一個不易讓人分心的環境。</p></blockquote><p>Mac上的iA Writer固然能很好地做到這一點，但作為一個初二學生，我確實也沒有那個經濟實力去買正版。我也不打算用盜版。我找到了一個類似的軟件，叫做 <a href="http://write4Me.sinaapp.com/">4Me寫字板</a>。它基於CodeMirror。但是，它和 iA Writer的差距未免有點大……</p><p>但這卻給了我一個啟發：為什麼不自己動手試著用CodeMirror製作一個Markdown編輯器呢？</p><p>於是我徵求了原作者同意之後，借著這次因新冠疫情宅家的時間，嘗試自己以4Me寫字板為藍本，製作自己的寫作工具。於是我做出了這個Markdown編輯器——Clear Writer，意味著希望人們使用它時，可以讓人理清自己的思維。</p><p>另外，Clear Writer的一個很重要的一點是它支持實时Markdown語法。很多的所謂實时Markdown，我都不是很喜歡——因為它們會把Markdown格式標記隱去。我不喜歡這樣，我喜歡讓格式牢牢掌控在使用者的手裡。</p><h2 id="h2-clear-writer-"><a name="Clear Writer 的特點" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Clear Writer 的特點</h2><ul><li>全自動保存；</li><li>所見即所得的實时MarkDown，以及標題懸掛；<br>-支持亮色/暗色模式；<br>-漂亮的隱藏式滾動條；<br>-支持簡體中文/繁體中文/英文三種語言；<br>-支持開啟/關閉行號；<br>-高亮當前段落；<br>-漂亮的光標閃動和跳動效果；<br>-介面自我調整；<br>-內容全部在本地緩存，完全隱私保護；<br>-支持匯出<code>.txt</code>、<code>.md</code>、<code>.doc</code>、<code>.html</code>、帶CSS的<code>html</code> 5種格式；<br>-平滑滾動；<br>-可讓你立即進入狀態的”閃念“功能（v1.7+）</li></ul><h2 id="h2-u4F7Fu7528u6280u5DE7"><a name="使用技巧" class="reference-link"></a><span class="header-link octicon octicon-link"></span>使用技巧</h2><ul><li>點擊頂欄上的全屏按鈕或按下<code>F11</code>（或<code>Fn + F11</code>）切入全屏，安心寫作；</li><li>滑鼠移動至頂部時顯示頂欄，其中可以切換亮/暗色模式、行號、語言等；</li><li>點擊頂欄上的圖釘<code>📌</code>按鈕可以固定頂欄，使其不自動隱藏；</li><li>右上角有<code>另存為…</code>按鈕，點擊可以將文字匯出為其他格式文字；</li><li>點擊左上角的<code>Clear Writer</code>會在側邊欄顯示你現在正在看的這段文字，再次點擊<code>Clear Writer</code>隱藏側邊欄；</li><li>可撤銷最近的2000次操作，無懼修改；</li><li>Clear Writer全自動保存，正常情况下每3分鐘自動保存一次，在關閉的時候也會再次自動保存一次。實在不放心，還可以<code>Ctrl + S</code>手動保存；<br>-查找：<code>Ctrl + F</code>；<br>-查找下一個：<code>Ctrl + G</code>；<br>-查找上一個：<code>Shift + Ctrl + G</code>；<br>-替換：<code>Shift + Ctrl + F</code>；<br>-替換全部：<code>Shift + Ctrl + R</code>。</li></ul><h2 id="h2-u76F8u5BB9u6027"><a name="相容性" class="reference-link"></a><span class="header-link octicon octicon-link"></span>相容性</h2><p>Windows 7及以上。</p><h2 id="h2-u95DCu65BC"><a name="關於" class="reference-link"></a><span class="header-link octicon octicon-link"></span>關於</h2><p>Clear Writer使用GNU General Public License 3.0進行許可。</p><p>編碼工具：Visual Studio & Visual Studio Code<br>安裝包製作工具：NSIS</p><h3 id="h3-clear-writer-"><a name="Clear Writer的誕生離不開：" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Clear Writer的誕生離不開：</h3><ul><li>西文字體：NeverMind（SIL Open Font License 1.1）；</li><li>中文&等距字體：更紗黑體（SIL Open Font License 1.1）；</li><li>編輯器基礎：CodeMirror（MIT License）；</li><li>Markdown渲染：editor.md（MIT License）；</li><li>構建基礎：Electron（MIT License）；</li><li>图标：Font Awsome (Font Awesome Free License)；</li><li>藍本：4Me Writer，無協定狀態，但已經開發者口頭許可。</li></ul><p>衷心感謝所有為本項目提供支援與幫助的人。</p>'
      );
      $("#cut").html("剪切");
      $("#copy").html("複製");
      $("#paste").html("粘貼");
      $("#selectall").html("全選");
      $("#bold").html("粗體");
      $("#italic").html("斜體");
      $("#linethrough").html("删除線");
      $("#hyperlink").html("超連結");
      $("#undo").html("撤銷");
      $("#title_of_main_color").html("主題色");
      $("#fold").html("折疊");
      $("#redo").html("重做");
      $("#advance").html("高級");
      $("#title_of_disable_animation").html("禁用動效");
      $("#title_of_settings").html("設定");
      $("#title_of_look").html("外觀");
      $("#set_main_color").html("設定...");
      $("#title_of_font").html("字體");
      $("#experiment").html("實驗性功能");
      $("#experiment-warning").html(
        "警告: 以下為實驗性功能！啟用這些選項可能導致程式崩潰或卡頓。"
      );
      $("#title_of_acrylic").html("啟用亞克力效果（Win10 1803+）");
      $("#title_of_opacity").html("視窗背景不透明度");
      $("#title_of_dev").html("開發人員工具");
      $("#dev_tools").html("開啟");
      $("#backup_and_sync").html("備份與同步");
      $("#import_from_file").html("從檔案導入數據");
      $("#export_to_file").html("匯出數據到檔案");
      $("#sync_start_btn").html("使用 Github 帳戶登入");
      $("#sync_upload").html("備份數據到雲端");
      $("#sync_download").html("下載數據到本地");
      $("#gitee_sync_start_btn").html("使用 Gitee 帳戶登入");
      $("#gitee_sync_upload").html("備份數據到雲端");
      $("#gitee_sync_download").html("下載數據到本地");
      $("#title_of_css").html("自定義 CSS");
      $("#css_btn").html("編輯...");
      $("#title_of_update").html("更新");
      $("#update").html("檢查更新");
      $("#current_vertion").html(`當前版本：${VERSION}`);
      $("#open").attr("title", "打開隨筆清單【Ctrl + O】");
      $("#feedback").attr("title", "提供迴響");
      $("#open_settings").attr("title", "打開設定");
      $("#topbar_undo").attr("title", "撤銷【Ctrl + Z】");
      $("#topbar_redo").attr("title", "重做【Ctrl + Y 或 Ctrl + Shift + Z】");
      $("#topbar_bold").attr(
        "title",
        "#加粗#使用一對“**”或一對“__”來包裹被加粗的文字【Ctrl + B】"
      );
      $("#topbar_italic").attr(
        "title",
        "#斜體#使用一對“*”或一對“_”來包裹斜體的文字【Ctrl + I】"
      );
      $("#topbar_strikethrough").attr(
        "title",
        "#删除線#使用一對“~~”來包裹添加删除線的文字"
      );
      $("#topbar_link").attr(
        "title",
        "#超連結#使用一對“[”“]”來包裹超連結的顯示文字,其後緊跟用“(”“)”包裹的URL【Ctrl + K】"
      );
      $("#find").attr("title", "查找【Ctrl + F】");
      $("#replace").attr("title", "替換【Ctrl + H 或 Ctrl + Shift + F】");
      $("#preview").attr("title", "預覽");
      $("#counter").attr("title", "文字計數器");
      $("#title").attr(
        "title",
        "#關於#點擊查看Clear Writer的開發歷程和更新日誌"
      );
      $("#save_btn").attr(
        "title",
        "#另存為#將隨筆另存為 .md、.txt、.doc、.html 等格式"
      );
      $("#minimize").attr("title", "最小化");
      $("#maxmize").attr("title", "最大化");
      $("#fullscreen").attr("title", "全屏");
      $("#close").attr("title", "關閉");
      $("#gitee_sign_out_btn").attr("title", "登出");
      $("#sign_out_btn").attr("title", "登出");
      break;
    case "zh-cn":
      DARK = "暗"; //暗色模式的显示名称
      LIGHT = "亮"; //亮色模式的显示名称
      ON = "开"; //开启状态的显示名称
      OFF = "关"; //关闭状态的显示名称
      SAVED_AT = "已保存于 "; //手动保存时在右上角的显示名称
      AUTO_SAVED_AT = "已自动保存于 "; //自动保存时在右上角的显示名称
      CHOOSE_FILE = "选择随笔";
      NEW = "新建";
      ENSURE_DEL = "确定永久删除？此操作不可撤销。";
      OK = YES = "确定";
      FNAME = "重命名";
      SEARCH = "查找";
      REPLACE = "替换";
      SEARCHTIP = "使用 /re/ 语法以使用正则表达式搜索，<br />按下 Esc 以退出";
      RWITH = "替换为";
      CREATE_FROM_FILE = "从文件新建...";
      RELSE_MOUSE = "请放开鼠标";
      DRAG_HERE = "请将文件拖拽至此";
      SUCCEED = "读取成功";
      ALL = "全部";
      CANCEL = "取消";
      SKIP = "跳过";
      PREVIEW = "预览";
      COUNT = "统计";
      WORD = "字词数";
      CHAR = "字符数";
      TIME = "预计阅读时长";
      WITH_SPACE = " (包含空格)";
      SAVE_AS = "另存为...";
      CHOOSE_MAIN_COLOR = "选择主题色";
      DIY_COLOR = "选择颜色...";
      SET_TO_DEFALT = "设为默认值";
      AUTO = "跟随系统";
      WITH_STYLE = "（带样式）";
      QUICK_NOTE = "闪念";
      TERM = "等距字体";
      DEFALT = "默认字体";
      OR = "或";
      CLICK_TO_UPLOAD = "点击此处打开文件";
      THIS_IS_A_BACKUP =
        "这是 Clear Writer 编辑器的数据备份文件，其中包含了用户除登录信息外的所有文章和用户设置。你可以在 [Clear Writer 的官网](https://henrylin666.gitee.io/clearwriter/)了解到更多信息。此备份由 Clear Writer 版本 ${VERSION} 创建于 ${date}。";
      FILE_LIST_TITLE = "随笔列表";
      NOTHING_TO_COUNT = "没有可供统计的文本";
      MAXMIZE = "最大化";
      RESTORE = "还原";
      NEW_VER = "检测到新版本 - ";
      UPDATE_NOW = "立即更新";
      SHOW_NEXT_TIME = "下次一定";
      DONT_SHOW_AGAIN = "此版本不再提示";
      REPLACE_CURR_DATA = "确定覆盖当前数据？";
      IMPORT_CANCELED = "导入已取消";
      COLLECTING_DATA = "正在准备数据";
      SENDING_DATA = "正在发送数据";
      SEND_SUCCEEDED = "已成功备份至云端";
      NET_ERR = "网络异常，请重试";
      PULLING_LIST = "正在拉取备份列表";
      CHOOSE_BACKUP = "选择一个备份";
      DOWNLOADING_DATA = "正在下载数据";
      PARSING_DATA = "正在解析数据";
      NEWEST = "当前已是最新版本";
      FILE_BROKEN = "文件已损坏";
      GENERATE =
        "使用 <a href='https://clearwriter.gitee.io/'>Clear Writer</a> 生成";
      SYNC_FAILED = "同步失败";
      SYNC_FAILED_REASON =
        "这并不是 Clear Writer 的问题。Gitee 服务器返回了 500 错误，这表明服务器无法处理您的随笔。<br/>Gitee 的同步服务不支持 Emoji 和某些特殊字符，但 Gitee 并未具体说明哪些符号会导致此类异常。因此您可能需要在您的随笔中自行查找可能导致错误的字符。您也可以考虑使用 Github 同步服务。";
      $("#title_of_theme").html("主题");
      $("#title_of_num").html("行号");
      $("#title_of_lang").html("语言");
      $("#lang").html("简体中文");
      $("#save_btn").html("另存为...");
      $("#about").html(
        '<h1 id="h1-welcome-to-clear-writer-markdown-"><a name="Welcome to Clear Writer，这是一个沉浸式 Markdown 写作软件。" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Welcome to Clear Writer，这是一个沉浸式 Markdown 写作软件。</h1><h2 id="h2--clear-writer"><a name="为什么编写 Clear Writer" class="reference-link"></a><span class="header-link octicon octicon-link"></span>为什么编写 Clear Writer</h2><p>我开了我自己的博客之后，一直苦于 Windows 端没有我喜欢的 Markdown 编辑器。</p><blockquote><p>其实写作，最需要的并不是很好很强大的工具，而是一个不易让人分心的环境。</p></blockquote><p>Mac上的 iA Writer 固然能很好地做到这一点，但作为一个初二学生，我确实也没有那个经济实力去买正版。我也不打算用盗版。我找到了一个类似的软件，叫做 <a href="http://write4Me.sinaapp.com/">4Me 写字板</a>。它基于 CodeMirror。但是，它和 iA Writer 的差距未免有点大……</p><p>但这却给了我一个启发：为什么不自己动手试着用 CodeMirror 制作一个 Markdown 编辑器呢？</p><p>于是我征求了原作者同意之后，借着这次因新冠疫情宅家的时间，尝试自己以 4Me 写字板为蓝本，制作自己的写作工具。于是我做出了这个 Markdown 编辑器 —— Clear Writer，意味着希望人们使用它时，可以让人理清自己的思维。</p><p>另外，Clear Writer 的一个很重要的一点是它支持实时 Markdown 语法。很多的所谓实时 Markdown，我都不是很喜欢——因为它们会把 Markdown 格式标记隐去。我不喜欢这样，我喜欢让格式牢牢掌控在使用者的手里。</p><h2 id="h2-clear-writer-"><a name="Clear Writer 的特点" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Clear Writer 的特点</h2><ul><li>全自动保存；</li><li>所见即所得的实时 MarkDown，以及标题悬挂；</li><li>支持亮色 / 暗色模式；</li><li>漂亮的隐藏式滚动条；</li><li>支持简体中文 / 繁体中文 / 英文三种语言；</li><li>支持开启 / 关闭行号；</li><li>高亮当前段落；</li><li>漂亮的光标闪动和跳动效果；</li><li>界面自适应；</li><li>内容全部在本地缓存，完全隐私保护；</li><li>支持导出 <code>.txt</code>、<code>.md</code>、<code>.doc</code>、<code>.html</code>、带 CSS 的 <code>html</code> 5 种格式；</li><li>平滑滚动；</li><li>可让你立即进入状态的”闪念“功能（v1.7+）。</li></ul><h2 id="h2-u4F7Fu7528u6280u5DE7"><a name="使用技巧" class="reference-link"></a><span class="header-link octicon octicon-link"></span>使用技巧</h2><ul><li>点击顶栏上的全屏按钮或按下 <code>F11</code>（或 <code>Fn + F11</code>）切入全屏，安心写作；</li><li>鼠标移动至顶部时显示顶栏，其中可以切换亮/暗色模式、行号、语言等；</li><li>点击顶栏上的图钉 <code>📌</code> 按钮可以固定顶栏，使其不自动隐藏；</li><li>右上角有 <code>另存为...</code> 按钮，点击可以将文字导出为其他格式文本；</li><li>点击左上角的 <code>Clear Writer</code> 会在侧边栏显示你现在正在看的这段文字，再次点击 <code>Clear Writer</code> 隐藏侧边栏；</li><li>可撤销最近的 2000 次操作，无惧修改；</li><li>Clear Writer 全自动保存，正常情况下每 3 分钟自动保存一次，在关闭的时候也会再次自动保存一次。实在不放心，还可以 <code>Ctrl + S</code> 手动保存；</li><li>查找：<code>Ctrl + F</code>；</li><li>查找下一个：<code>Ctrl + G</code>；</li><li>查找上一个：<code>Shift + Ctrl + G</code>；</li><li>替换：<code>Shift + Ctrl + F</code>；</li><li>替换全部：<code>Shift + Ctrl + R</code>。</li></ul><h2 id="h2-u517Cu5BB9u6027"><a name="兼容性" class="reference-link"></a><span class="header-link octicon octicon-link"></span>兼容性</h2><p>Windows 7 及以上。</p><h2 id="h2-u5173u4E8E"><a name="关于" class="reference-link"></a><span class="header-link octicon octicon-link"></span>关于</h2><p>Clear Writer 使用 GNU General Public License 3.0 进行许可。</p><p>编码工具：Visual Studio & Visual Studio Code<br>安装包制作工具：NSIS</p><h3 id="h3-clear-writer-"><a name="Clear Writer 的诞生离不开：" class="reference-link"></a><span class="header-link octicon octicon-link"></span>Clear Writer 的诞生离不开：</h3><ul><li>西文字体：NeverMind（SIL Open Font License 1.1）；</li><li>中文&等宽字体：更纱黑体（SIL Open Font License 1.1）；</li><li>编辑器基础：CodeMirror（MIT License）；</li><li>Markdown 渲染：editor.md（MIT License）；</li><li>构建基础：Electron（MIT License）；</li><li>图标: Font Awsome（Font Awesome Free License）；</li><li>蓝本：4Me Writer，无协议状态，但已经开发者口头许可。</li></ul><p>衷心感谢所有为本项目提供支持与帮助的人。</p><h2 id="h2-u66F4u65B0u65E5u5FD7"><a name="更新日志" class="reference-link"></a><span class="header-link octicon octicon-link"></span>更新日志</h2>   <h3 id="h3-v2-0" title=""><a name="v2.0" class="reference-link"></a><span class="header-link octicon octicon-link"></span>v2.0</h3><ul><li title="">新增亚克力效果选项（需要在“设置”中手动开启，仅支持 Win10 1803+，不支持全屏模式）；</li><li title="">弃用思源黑体，将内置默认字体改为更纱黑体 UI SC（仍基于思源黑体），提升字体渲染效果及字库大小；</li><li title="">全面支持多光标输入（按下 Ctrl 并左键单击可以新建光标）；</li><li title="">修复默认字体下输入代码块需要等待一会儿才能加载出等距字体的问题</li><li title="">上线全新反馈社区；</li><li title="">修复了使用微软拼音 IME 输入时拼音采用等距字体显示的问题；</li><li title="">修复了使用微软拼音 IME 输入时选字框遮挡当前拼音的问题；</li><li title="">修复了语言为英语时预览功能异常的问题；</li><li title="">优化了一些动画效果的速度曲线；</li><li title="">新增开发人员工具入口，方便使用时定位 bug；</li><li title="">优化程序图标显示，解决圆角部分的锯齿现象；</li><li title="">新增替换快捷键 <code>Ctrl+H</code>；</li><li>实现响应式 UI，优化在小窗口下的体验；</li><li>优化打开超长文件名的文件时标题栏的显示；</li><li>颠倒暗色模式的主背景色和副背景色，优化体验，同时进行了按钮样式的微调；</li><li>修复了选中多行文本的时候选中部分色块在左侧会溢出的状况；</li><li>修复了选中多行文本的时候出现色块堆积的状况；</li><li>新增右键菜单项目图标；</li><li>新增删除文件时的确认动画；</li><li>修复了启动时加载 logo 无法使用主题色的情况；</li><li>优化替换时的工具栏，使其与查找工具栏统一，同时在替换的时候增加高亮；</li><li>新增双色图标；</li><li>修复了使用微软拼音 IME 时，选字框会遮挡文字的情况；</li><li>新增英文下的自动括号匹配；</li><li>实现在文件资源管理器中双击 <code>.md</code> 文件后直接用 Clear Writer 打开；</li><li>修复了在暗色模式下删除线显示不明显的问题；</li><li>新增开启行号时，当前行行号高亮效果；</li><li>新增自定义 CSS 功能，允许用户自己定义 Clear Writer 的 CSS 代码；</li><li>修改字体存储方式，缩小程序大小，提高渲染速度；</li><li>优化打开右键菜单时的动画；</li><li>优化预览窗口内容样式，增强可读性；</li><li>优化预览中 To-do 列表复选框的样式；</li><li>优化弹窗关闭按钮的样式；</li><li>新增按钮鼠标悬浮提示；</li><li>优化左侧栏的动画效果；</li><li>修复顶栏左侧的彩色按钮在 Win 7 下显示为黑白的情况；</li><li>加入自动检查更新的组件；</li><li>新增设置面板中的图标；</li><li>实现利用 Github Gist 同步文件和设置；</li><li>新增语言：英语（英国）</li></ul><p>另外由于开发者初三了，所以未来的一年里可能不会再有任何更新了，如果有遇到 bug 或者想提供一些新点子，可以在 Clear Writer 反馈论坛里面发帖。中考之后，如果还有时间的话，我会继续尝试将 Clear Writer 做得更好。由于跨域访问限制的存在，而我又租不起服务器，Clear Writer Online 已经搁浅，未来做成微信小程序的可能性更大，特此说明。</p><p>2020 年 8 月<br>Henrylin666</p><h3 id="h3-clear-writer-v1-8-"><a name="Clear Writer v1.8 更新日志" class="reference-link"></a><span class="header-link octicon octicon-link"></span>v1.8</h3><ul><li>引入等距更纱黑体作为等宽字体；</li><li>新增统一的设置面板；</li><li>支持在全局使用等宽字体；</li><li>新增查找时的工具条；</li><li>优化超长随笔名的显示；</li><li>优化启动时长；</li><li>顶栏改版，使用图标代替文字，取消标签页</li></ul>   <h3 id="h3-v1-7"><a name="v1.7" class="reference-link"></a><span class="header-link octicon octicon-link"></span>v1.7</h3><ul><li>新增新建随笔时的回车快捷确认；</li><li>修复标题中插入 HTML 标签时的异常；</li><li>新增禁用动画选项，以保证能在低配置环境下运行；</li><li>新增查找栏的动画效果；</li><li>修复程序体积过大的问题；</li><li>大幅缩短程序加载时长；</li><li>新增 <code>html</code> 和 <code>带 CSS 的 html</code> 的随笔另存支持。</li></ul><h3 id="h3-v1-6"><a name="v1.6" class="reference-link"></a><span class="header-link octicon octicon-link"></span>v1.6</h3><ul><li>优化主题色选择，支持直接跟随系统主题色（仅 Windows 10）；</li><li>优化亮色/暗色模式适配，支持跟随系统亮色/暗色模式（仅 Windows 10）；</li><li>新增全新的开始屏幕磁贴（仅 Windows 10）；</li><li>修复“预览”窗格中 HTML 代码块未被正常高亮的问题；</li><li>在正文编辑的代码块中使用等宽字体 Consolas，带来原汁原味的代码风；</li><li>新增对 Python、PHP、ruby 和 go 语言的代码块高亮支持；</li></ul><h3 id="h3-v1-5"><a name="v1.5" class="reference-link"></a><span class="header-link octicon octicon-link"></span>v1.5</h3><ul><li>修复两个弹窗并行时的一个 BUG；</li><li>修复“折叠”“剪切”按钮未翻译的问题；</li><li>修复了全屏模式下点击最大化/还原按钮无反应的 BUG；</li><li>新增打开、切换随笔时标题栏的切换动画；</li><li>新增“另存为”格式：.md、.doc；</li><li>新增预览时的代码块高亮；</li><li>新增删除随笔时的“取消”按钮；</li><li>新增覆盖输入模式下（按Insert键进入）的特有光标，以和插入模式区别开来</li></ul><h3 id="h3-v1-4"><a name="v1.4" class="reference-link"></a><span class="header-link octicon octicon-link"></span>v1.4</h3><ul><li>修复了在重命名随笔之后随笔内容丢失的 BUG； </li><li>修复了在切换随笔后快捷键定义重复现象的 BUG；</li><li>抛弃系统自带的标题栏，自己做了一个更漂亮的；</li><li>新增统计功能（统计的是最终生成的文本，不包含 Markdown 语法字符）。</li></ul><h3 id="h3-v1-3"><a name="v1.3" class="reference-link"></a><span class="header-link octicon octicon-link"></span>v1.3</h3><ul><li>更新内核为 Chromium 82；</li><li>支持更改主题色（”主题“组下），自定义你的 Clear Writer；</li><li>标题栏优化：鼠标悬停在组标题上时才显示按钮；</li><li>大幅缩短切换随笔、切换语言的用时；</li><li>优化语言切换方式；</li><li>增加右键菜单项目，现支持 11 种操作，如加粗、斜体等，解救鼠标党；</li><li>在标题栏的”工具“组下新增”查找“”查找下一个“”替换“按钮，解救鼠标党；</li><li>新增 Markdown 标题段落折叠。</li></ul><h3 id="h3-v1-2"><a name="v1.2" class="reference-link"></a><span class="header-link octicon octicon-link"></span>v1.2</h3><ul><li>新图标；</li><li>新增预览窗口。</li></ul><h3 id="h3-v1-1"><a name="v1.1" class="reference-link"></a><span class="header-link octicon octicon-link"></span>v1.1</h3><ul><li>新增右键菜单；</li><li>新增“从文件新建”功能。</li></ul>'
      );
      $("#copy").html("复制");
      $("#paste").html("粘贴");
      $("#cut").html("剪切");
      $("#selectall").html("全选");
      $("#bold").html("粗体");
      $("#italic").html("斜体");
      $("#linethrough").html("删除线");
      $("#hyperlink").html("超链接");
      $("#undo").html("撤销");
      $("#redo").html("重做");
      $("#title_of_main_color").html("主题色");
      $("#fold").html("折叠");
      $("#advance").html("高级");
      $("#title_of_disable_animation").html("禁用动画");
      $("#title_of_settings").html("设置");
      $("#title_of_look").html("外观");
      $("#set_main_color").html("设置...");
      $("#title_of_font").html("字体");
      $("#experiment").html("实验性功能");
      $("#experiment-warning").html(
        "警告: 以下为实验性功能！启用这些选项可能导致程序崩溃或卡顿。"
      );
      $("#title_of_acrylic").html("启用亚克力效果（Win10 1803+）");
      $("#title_of_opacity").html("窗口背景不透明度");
      $("#title_of_dev").html("开发人员工具");
      $("#dev_tools").html("打开");
      $("#backup_and_sync").html("备份与同步");
      $("#import_from_file").html("从文件导入数据");
      $("#export_to_file").html("导出数据到文件");
      $("#sync_start_btn").html("使用 Github 账户登录");
      $("#sync_upload").html("备份数据到云端");
      $("#sync_download").html("下载数据到本地");
      $("#gitee_sync_start_btn").html("使用 Github 账户登录");
      $("#gitee_sync_upload").html("备份数据到云端");
      $("#gitee_sync_download").html("下载数据到本地");
      $("#title_of_css").html("自定义 CSS");
      $("#css_btn").html("编辑...");
      $("#title_of_update").html("更新");
      $("#update").html("检查更新");
      $("#current_vertion").html(`当前版本：${VERSION}`);
      $("#open").attr("title", "打开随笔列表【Ctrl + O】");
      $("#feedback").attr("title", "提供反馈");
      $("#open_settings").attr("title", "打开设置");
      $("#topbar_undo").attr("title", "撤销【Ctrl + Z】");
      $("#topbar_redo").attr("title", "重做【Ctrl + Y 或 Ctrl + Shift + Z】");
      $("#topbar_bold").attr(
        "title",
        "#加粗#使用一对“**”或一对“__”来包裹被加粗的文本【Ctrl + B】"
      );
      $("#topbar_italic").attr(
        "title",
        "#斜体#使用一对“*”或一对“_”来包裹斜体的文本【Ctrl + I】"
      );
      $("#topbar_strikethrough").attr(
        "title",
        "#删除线#使用一对“~~”来包裹添加删除线的文本"
      );
      $("#topbar_link").attr(
        "title",
        "#超链接#使用一对“[”“]”来包裹超链接的显示文本，其后紧跟用“(”“)”包裹的 URL【Ctrl + K】"
      );
      $("#find").attr("title", "查找【Ctrl + F】");
      $("#replace").attr("title", "替换【Ctrl + H 或 Ctrl + Shift + F】");
      $("#preview").attr("title", "预览");
      $("#counter").attr("title", "文本计数器");
      $("#title").attr(
        "title",
        "#关于#点击查看 Clear Writer 的开发历程和更新日志"
      );
      $("#save_btn").attr(
        "title",
        "#另存为#将随笔另存为 .md、.txt、.doc、.html 等格式"
      );
      $("#minimize").attr("title", "最小化");
      $("#maxmize").attr("title", "最大化");
      $("#fullscreen").attr("title", "全屏");
      $("#close").attr("title", "关闭");
      $("#gitee_sign_out_btn").attr("title", "登出");
      $("#sign_out_btn").attr("title", "登出");
      break;
  }
  reset_switch();
}
